### ISSUE TITLE
Error: bind EADDRINUSE

### ISSUE THREAD

**Issue by jgarber** [Marak/natman#3]
I get an error that the address is in use. I can't see how it would be on my local machine, though.

```
/usr/local/share/npm/bin/natman -> /usr/local/share/npm/lib/node_modules/natman/bin/natman
natman@0.0.2 /usr/local/share/npm/lib/node_modules/natman
├── colors@0.6.0-1
├── revalidator@0.1.5
├── nat-pmp@0.0.1 (debug@0.7.0)
├── utile@0.1.6 (deep-equal@0.0.0, rimraf@1.0.9, async@0.1.22, mkdirp@0.3.4, ncp@0.2.6, i@0.3.1)
├── netroute@0.2.2 (bindings@1.0.0)
├── nat-upnp@0.2.9 (ip@0.0.1, async@0.1.22, request@2.10.0, xml2js@0.1.14)
└── flatiron@0.3.0 (pkginfo@0.2.3, director@1.1.6, optimist@0.3.4, broadway@0.2.5, prompt@0.2.8)
╭─@Jasons-MacBook-Air.local ~/node_modules ‹ruby-1.9.3› 
╰─ natman open 22 8000
info:    Creating NAT...
warn:    Using gateway: 10.0.1.1
help:    You can manually specify a gateway with -g argument
warn:    Attempting to connect... 

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: bind EADDRINUSE
    at errnoException (dgram.js:356:11)
    at Socket.bind (dgram.js:123:15)
    at lookup (dgram.js:49:12)
    at UDP.lookup4 [as lookup] (dgram.js:59:10)
    at Socket.bind (dgram.js:120:16)
    at new Client (/usr/local/share/npm/lib/node_modules/natman/node_modules/nat-pmp/index.js:78:15)
    at Object.exports.connect (/usr/local/share/npm/lib/node_modules/natman/node_modules/nat-pmp/index.js:55:10)
    at new exports.Nat (/usr/local/share/npm/lib/node_modules/natman/lib/natman.js:12:17)
    at Object.natman.createNat (/usr/local/share/npm/lib/node_modules/natman/lib/natman.js:24:13)
    at app.commands.open (/usr/local/share/npm/lib/node_modules/natman/bin/natman:116:19)
╭─@Jasons-MacBook-Air.local ~/node_modules ‹ruby-1.9.3› 
╰─ natman open 22 9987                                                                                                                      1 ↵
info:    Creating NAT...
warn:    Using gateway: 10.0.1.1
help:    You can manually specify a gateway with -g argument
warn:    Attempting to connect... 

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: bind EADDRINUSE
    at errnoException (dgram.js:356:11)
    at Socket.bind (dgram.js:123:15)
    at lookup (dgram.js:49:12)
    at UDP.lookup4 [as lookup] (dgram.js:59:10)
    at Socket.bind (dgram.js:120:16)
    at new Client (/usr/local/share/npm/lib/node_modules/natman/node_modules/nat-pmp/index.js:78:15)
    at Object.exports.connect (/usr/local/share/npm/lib/node_modules/natman/node_modules/nat-pmp/index.js:55:10)
    at new exports.Nat (/usr/local/share/npm/lib/node_modules/natman/lib/natman.js:12:17)
    at Object.natman.createNat (/usr/local/share/npm/lib/node_modules/natman/lib/natman.js:24:13)
    at app.commands.open (/usr/local/share/npm/lib/node_modules/natman/bin/natman:116:19)
╭─@Jasons-MacBook-Air.local ~/node_modules ‹ruby-1.9.3› 
╰─ lsof -i | grep LISTEN                                                                                                                    1 ↵
postgres    272 jasongarber    5u  IPv6 0x4779b6c855439443      0t0  TCP localhost:postgresql (LISTEN)
postgres    272 jasongarber    6u  IPv4 0x4779b6c85802bbb3      0t0  TCP localhost:postgresql (LISTEN)
postgres    272 jasongarber    7u  IPv6 0x4779b6c8581f0fe3      0t0  TCP localhost:postgresql (LISTEN)
mongod      274 jasongarber    6u  IPv4 0x4779b6c85446279b      0t0  TCP localhost:28017 (LISTEN)
mongod      274 jasongarber    7u  IPv4 0x4779b6c85802dfcb      0t0  TCP localhost:27017 (LISTEN)
memcached   275 jasongarber   18u  IPv6 0x4779b6c855439823      0t0  TCP localhost:11211 (LISTEN)
memcached   275 jasongarber   19u  IPv4 0x4779b6c854462ed3      0t0  TCP localhost:11211 (LISTEN)
node        276 jasongarber    8u  IPv4 0x4779b6c858a7da23      0t0  TCP *:20559 (LISTEN)
SpotifyWe   277 jasongarber    6u  IPv4 0x4779b6c85d3d515b      0t0  TCP localhost:4370 (LISTEN)
SpotifyWe   277 jasongarber    7u  IPv4 0x4779b6c85e4dd79b      0t0  TCP localhost:4380 (LISTEN)
1Password   381 jasongarber    6u  IPv4 0x4779b6c85cd9ca23      0t0  TCP localhost:6258 (LISTEN)
1Password   381 jasongarber    7u  IPv6 0x4779b6c8581f0443      0t0  TCP localhost:6258 (LISTEN)
mysqld      388 jasongarber   12u  IPv6 0x4779b6c8581f0c03      0t0  TCP *:mysql (LISTEN)
Growl       401 jasongarber    4u  IPv4 0x4779b6c85802ad43      0t0  TCP localhost:23053 (LISTEN)
Growl       401 jasongarber    5u  IPv6 0x4779b6c8581f0823      0t0  TCP localhost:23053 (LISTEN)
```

**Comment by mohanwd** [comment]
Sorry, I too get the same error. when i uncomment "note.payload = {'messageFrom': 'Colomer'};"
